# 1.Importando librerias

In [1]:
!pip install matplotlib
!pip install seaborn
!pip install plotly

Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (0.13.1)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.10/dist-packages (from seaborn) (1.25.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.10/dist-packages (from seaborn) (1.5.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.10/dist-packages (from seaborn) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2->seaborn) (2023.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (5.15.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly) (8.2.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly) (23.2)

In [2]:
import pandas as pd
import numpy as np
import io

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [4]:
%matplotlib inline

In [5]:
import datetime
import warnings
warnings.filterwarnings('ignore')

# 2.Lectura csv en drive

In [6]:
#@title conectar a drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
#@title carga de los csv y guardarlos en una variable

total_turistas= pd.read_csv('/content/drive/MyDrive/Hosting/Hosting/Power BI/Muestreo Mercado/Apartamentos Turisticos/08dimNúmero de turistas según comunidad autónoma de destino principal.csv', encoding='utf-8',delimiter=';',  # Asumir que el delimitador es un punto y coma
    na_values='.',error_bad_lines=False
)
motivo_viaje = pd.read_csv('/content/drive/MyDrive/Hosting/Hosting/Power BI/Muestreo Mercado/Apartamentos Turisticos/10dimMotivo del viaje.csv', encoding='utf-8',delimiter=';',  # Asumir que el delimitador es un punto y coma
   na_values='.', error_bad_lines=False
)

tipo_alojamiento = pd.read_csv('/content/drive/MyDrive/Hosting/Hosting/Power BI/Muestreo Mercado/Apartamentos Turisticos/11DimTipo de alojamiento.csv', encoding='ISO-8859-1',delimiter=';',  # Asumir que el delimitador es un punto y coma
   na_values='.', error_bad_lines=False
)
gasto_medio = pd.read_csv('/content/drive/MyDrive/Hosting/Hosting/Power BI/Muestreo Mercado/Apartamentos Turisticos/14dimGasto medio.csv', encoding='utf-8',delimiter=';',  # Asumir que el delimitador es un punto y coma
   na_values='.', error_bad_lines=False
)

via_acceso = pd.read_csv('/content/drive/MyDrive/Hosting/Hosting/Power BI/Muestreo Mercado/Apartamentos Turisticos/12Dimvia acceso.csv', encoding='utf-8',delimiter=';',  # Asumir que el delimitador es un punto y coma
   na_values='.', error_bad_lines=False
)
duracion_viaje = pd.read_csv('/content/drive/MyDrive/Hosting/Hosting/Power BI/Muestreo Mercado/Apartamentos Turisticos/13dimDuración del viaje.csv', encoding='utf-8',delimiter=';',  # Asumir que el delimitador es un punto y coma
   na_values='.', error_bad_lines=False
)

# 3.-Tabla dimensión Datos

In [8]:
#@title Verificar las columnas de los csv

print("Columnas en total_turistas:")
print(total_turistas.columns)

print("\nColumnas en motivo_viaje:")
print(motivo_viaje.columns)

print("\nColumnas en tipo_alojamiento:")
print(tipo_alojamiento.columns)

print("\nColumnas en gasto_medio:")
print(gasto_medio.columns)

print("\nColumnas en via_acceso:")
print(via_acceso.columns)

print("\nColumnas en duracion_viaje:")
print(duracion_viaje.columns)

Columnas en total_turistas:
Index(['Comunidades autónomas', 'Tipo de dato', 'Periodo', 'Total'], dtype='object')

Columnas en motivo_viaje:
Index(['Comunidad autónoma de destino', 'Motivo del viaje', 'Periodo',
       'Total'],
      dtype='object')

Columnas en tipo_alojamiento:
Index(['Comunidad autónoma de destino', 'Tipo de alojamiento', 'Periodo',
       'Total'],
      dtype='object')

Columnas en gasto_medio:
Index(['Comunidad autónoma de residencia', 'Tipo de alojamiento',
       'Concepto turístico', 'Tipo de dato', 'Periodo', 'año', 'Total'],
      dtype='object')

Columnas en via_acceso:
Index(['Vía de acceso', 'Comunidad autónoma de destino', 'Periodo', 'Total'], dtype='object')

Columnas en duracion_viaje:
Index(['Vía de acceso', 'Comunidad autónoma de destino', 'Motivo del viaje',
       'Tipo de alojamiento', 'Forma de organización del viaje',
       'Duración del viaje', 'País de residencia', 'Periodo', 'Total'],
      dtype='object')



---


**Desde aqui se hace el analisis y se decide que con la tabla de Gasto Medio no se va a trabajar porque la collumna "Comunidad autónoma de residencia" da información diferente a lo que estamos buscando en este caso.**

---

In [9]:
total_turistas

    Comunidades autónomas             Tipo de dato  Periodo       Total
0                   Total                Dato base     2023  85.056.528
1                   Total                Dato base     2022  71.659.281
2                   Total                Dato base     2021  31.180.802
3                   Total                Dato base     2020  18.933.103
4                   Total                Dato base     2019  83.509.153
..                    ...                      ...      ...         ...
315            19 Melilla  Tasa de variación anual     2020         NaN
316            19 Melilla  Tasa de variación anual     2019         NaN
317            19 Melilla  Tasa de variación anual     2018         NaN
318            19 Melilla  Tasa de variación anual     2017         NaN
319            19 Melilla  Tasa de variación anual     2016         NaN

[320 rows x 4 columns]

In [10]:
motivo_viaje

,Comunidad autónoma de destino,Motivo del viaje,Periodo,Total
0,01 Andalucía,Negocios y otros motivos profesionales,2019M12,84140.0
1,01 Andalucía,Negocios y otros motivos profesionales,2019M11,64505.0
2,01 Andalucía,Negocios y otros motivos profesionales,2019M10,73955.0
3,01 Andalucía,Negocios y otros motivos profesionales,2019M09,86912.0
4,01 Andalucía,Negocios y otros motivos profesionales,2019M08,20461.0
...,...,...,...,...
1195,"13 Madrid, Comunidad de",Total de motivos del viaje,2023M05,704007.0
1196,"13 Madrid, Comunidad de",Total de motivos del viaje,2023M04,665430.0
1197,"13 Madrid, Comunidad de",Total de motivos del viaje,2023M03,594387.0
1198,"13 Madrid, Comunidad de",Total de motivos del viaje,2023M02,453469.0
1199,"13 Madrid, Comunidad de",Total de motivos del viaje,2023M01,528543.0

In [11]:
tipo_alojamiento

,Comunidad autónoma de destino,Tipo de alojamiento,Periodo,Total
0,01 Andalucía,Total de tipos de alojamiento,2023M12,625.424
1,01 Andalucía,Total de tipos de alojamiento,2023M11,719.412
2,01 Andalucía,Total de tipos de alojamiento,2023M10,1.242.189
3,01 Andalucía,Total de tipos de alojamiento,2023M09,1.310.845
4,01 Andalucía,Total de tipos de alojamiento,2023M08,1.441.316
...,...,...,...,...
2695,"13 Madrid, Comunidad de",Resto de no mercado,2019M05,NaN
2696,"13 Madrid, Comunidad de",Resto de no mercado,2019M04,NaN
2697,"13 Madrid, Comunidad de",Resto de no mercado,2019M03,NaN
2698,"13 Madrid, Comunidad de",Resto de no mercado,2019M02,NaN
2699,"13 Madrid, Comunidad de",Resto de no mercado,2019M01,NaN

In [12]:
duracion_viaje

,Vía de acceso,Comunidad autónoma de destino,Motivo del viaje,Tipo de alojamiento,Forma de organización del viaje,Duración del viaje,País de residencia,Periodo,Total
0,Total de vías de acceso,01 Andalucía,Total de motivos del viaje,Total de tipos de alojamiento,Total de formas de organización del viaje,Total noches,Total país de residencia,2023M12,625.424
1,Total de vías de acceso,01 Andalucía,Total de motivos del viaje,Total de tipos de alojamiento,Total de formas de organización del viaje,Total noches,Total país de residencia,2023M11,719.412
2,Total de vías de acceso,01 Andalucía,Total de motivos del viaje,Total de tipos de alojamiento,Total de formas de organización del viaje,Total noches,Total país de residencia,2023M10,1.242.189
3,Total de vías de acceso,01 Andalucía,Total de motivos del viaje,Total de tipos de alojamiento,Total de formas de organización del viaje,Total noches,Total país de residencia,2023M09,1.310.845
4,Total de vías de acceso,01 Andalucía,Total de motivos del viaje,Total de tipos de alojamiento,Total de formas de organización del viaje,Total noches,Total país de residencia,2023M08,1.441.316
...,...,...,...,...,...,...,...,...,...
1795,Total de vías de acceso,"13 Madrid, Comunidad de",Total de motivos del viaje,Total de tipos de alojamiento,Total de formas de organización del viaje,Más de 15 noches,Total país de residencia,2019M05,46.846
1796,Total de vías de acceso,"13 Madrid, Comunidad de",Total de motivos del viaje,Total de tipos de alojamiento,Total de formas de organización del viaje,Más de 15 noches,Total país de residencia,2019M04,35.451
1797,Total de vías de acceso,"13 Madrid, Comunidad de",Total de motivos del viaje,Total de tipos de alojamiento,Total de formas de organización del viaje,Más de 15 noches,Total país de residencia,2019M03,22.112
1798,Total de vías de acceso,"13 Madrid, Comunidad de",Total de motivos del viaje,Total de tipos de alojamiento,Total de formas de organización del viaje,Más de 15 noches,Total país de residencia,2019M02,21.203
1799,Total de vías de acceso,"13 Madrid, Comunidad de",Total de motivos del viaje,Total de tipos de alojamiento,Total de formas de organización del viaje,Más de 15 noches,Total país de residencia,2019M01,51.505

In [13]:
via_acceso

,Vía de acceso,Comunidad autónoma de destino,Periodo,Total
0,Total de vías de acceso,01 Andalucía,2023M12,625.424
1,Total de vías de acceso,01 Andalucía,2023M11,719.412
2,Total de vías de acceso,01 Andalucía,2023M10,1.242.189
3,Total de vías de acceso,01 Andalucía,2023M09,1.310.845
4,Total de vías de acceso,01 Andalucía,2023M08,1.441.316
...,...,...,...,...
1495,Tren,"13 Madrid, Comunidad de",2019M05,3.220
1496,Tren,"13 Madrid, Comunidad de",2019M04,3.754
1497,Tren,"13 Madrid, Comunidad de",2019M03,3.569
1498,Tren,"13 Madrid, Comunidad de",2019M02,2.721
1499,Tren,"13 Madrid, Comunidad de",2019M01,2.680

In [14]:
#@title Agrupar por la columna 'Tipo de dato' de la tabla via_acceso y contar el número de filas en cada grupo
summary = total_turistas.groupby('Tipo de dato').size()

# Mostrar el resumen agrupado
summary

Tipo de dato
Dato base                  160
Tasa de variación anual    160
dtype: int64

In [15]:
#@title Agrupar por la columna 'Motivo del viaje" de la tabla via_acceso y contar el número de filas en cada grupo
summary = motivo_viaje.groupby('Motivo del viaje').size()

# Mostrar el resumen agrupado
summary

Motivo del viaje
Negocios y otros motivos profesionales    300
Ocio, recreo y vacaciones                 300
Otros motivos                             300
Total de motivos del viaje                300
dtype: int64

In [16]:
#@title Agrupar por la columna "tipo_alojamiento" de la tabla via_acceso y contar el número de filas en cada grupo
summary = tipo_alojamiento.groupby('Tipo de alojamiento').size()

# Mostrar el resumen agrupado
summary

Tipo de alojamiento
De mercado                         300
Hotelero                           300
No de mercado                      300
Resto de mercado                   300
Resto de no mercado                300
Total de tipos de alojamiento      300
Vivienda de familiares o amigos    300
Vivienda en alquiler               300
Vivienda en propiedad              300
dtype: int64

In [17]:
#@title Agrupar por la columna "Vía de acceso" de la tabla via_acceso y contar el número de filas en cada grupo
summary = via_acceso.groupby('Vía de acceso').size()

# Mostrar el resumen agrupado
summary

Vía de acceso
Aeropuerto                 300
Carretera                  300
Puerto                     300
Total de vías de acceso    300
Tren                       300
dtype: int64

In [18]:
#@title Agrupar por la columna "Vía de acceso" de la tabla duracion_viaje y contar el número de filas en cada grupo
summary = duracion_viaje.groupby('Vía de acceso').size()

# Mostrar el resumen agrupado
summary

# Nota _: Se decide eliminar esta columna de la tabla a no aportar informacion.

Vía de acceso
Total de vías de acceso    1800
dtype: int64

In [19]:
#@title Agrupar por la columna "tipo de alojamiento'" de la tabla duracion_viaje y contar el número de filas en cada grupo
summary = duracion_viaje.groupby('Tipo de alojamiento').size()

# Mostrar el resumen agrupado
summary

# Nota _: Se decide eliminar esta columna de la tabla a no aportar informacion.

Tipo de alojamiento
Total de tipos de alojamiento    1800
dtype: int64

In [20]:
#@title Agrupar por la columna "Forma de organización del viaje'" de la tabla duracion_viaje y contar el número de filas en cada grupo
summary = duracion_viaje.groupby('Forma de organización del viaje').size()

# Mostrar el resumen agrupado
summary

# Nota _: Se decide eliminar esta columna de la tabla a no aportar informacion.

Forma de organización del viaje
Total de formas de organización del viaje    1800
dtype: int64

In [21]:
#@title Agrupar por la columna "País de residencia'" de la tabla duracion_viaje y contar el número de filas en cada grupo
summary = duracion_viaje.groupby('País de residencia').size()

# Mostrar el resumen agrupado
summary

# Nota _: Se decide eliminar esta columna de la tabla a no aportar informacion.

País de residencia
Total país de residencia    1800
dtype: int64

In [22]:
#@title Agrupar por la columna "País de residencia'" de la tabla duracion_viaje y contar el número de filas en cada grupo
summary = duracion_viaje.groupby('Duración del viaje').size()

# Mostrar el resumen agrupado
summary

Duración del viaje
1 noche             300
De 2 a 3 noches     300
De 4 a 7 noches     300
De 8 a 15 noches    300
Más de 15 noches    300
Total noches        300
dtype: int64

In [23]:
#@title Eliminar las columnas de DF duracion_viaje que hemos visto que no son necesarias

# Eliminar la columna 'Periodo' de cada DataFrame
try:
    duracion_viaje.drop(columns=['País de residencia', 'Forma de organización del viaje', 'Tipo de alojamiento', 'Vía de acceso','Motivo del viaje'], inplace=True)
except KeyError as e:
    print(f"Las columnas no se encuentran en duracion_viaje: {e}")

In [24]:
duracion_viaje

     Comunidad autónoma de destino Duración del viaje  Periodo      Total
0                     01 Andalucía       Total noches  2023M12    625.424
1                     01 Andalucía       Total noches  2023M11    719.412
2                     01 Andalucía       Total noches  2023M10  1.242.189
3                     01 Andalucía       Total noches  2023M09  1.310.845
4                     01 Andalucía       Total noches  2023M08  1.441.316
...                            ...                ...      ...        ...
1795       13 Madrid, Comunidad de   Más de 15 noches  2019M05     46.846
1796       13 Madrid, Comunidad de   Más de 15 noches  2019M04     35.451
1797       13 Madrid, Comunidad de   Más de 15 noches  2019M03     22.112
1798       13 Madrid, Comunidad de   Más de 15 noches  2019M02     21.203
1799       13 Madrid, Comunidad de   Más de 15 noches  2019M01     51.505

[1800 rows x 4 columns]

In [25]:
#@title Renombrar la columna Comunidades y Ciudades Autónomas	de viviendas_turistas

total_turistas = total_turistas.rename(columns={'Comunidades autónomas': 'Region'})

motivo_viaje = motivo_viaje.rename(columns={'Comunidad autónoma de destino': 'Region'})


via_acceso = via_acceso.rename(columns={'Comunidad autónoma de destino': 'Region'})


duracion_viaje = duracion_viaje.rename(columns={'Comunidad autónoma de destino': 'Region'})

tipo_alojamiento = tipo_alojamiento.rename(columns={'Comunidad autónoma de destino': 'Region'})

In [26]:
#@title Renombrar la columna Periodo	de total_turistas
total_turistas= total_turistas.rename(columns={'Periodo': 'Año'})

In [27]:
#@title Eliminar el código numérico de la columna Region de los DF delante de los nombres

total_turistas['Region'] = total_turistas['Region'].str.replace(r'^\d+\s', '', regex=True)
motivo_viaje['Region'] = motivo_viaje['Region'].str.replace(r'^\d+\s', '', regex=True)
via_acceso['Region'] = via_acceso['Region'].str.replace(r'^\d+\s', '', regex=True)
duracion_viaje['Region'] = duracion_viaje['Region'].str.replace(r'^\d+\s', '', regex=True)
tipo_alojamiento['Region'] = tipo_alojamiento['Region'].str.replace(r'^\d+\s', '', regex=True)

In [28]:
# Mostrar el DataFrame modificado
#Agrupar por la columna "REgion y contar el número de filas en cada grupo
summary = total_turistas.groupby('Region').size()

# Mostrar el resumen agrupado
summary

Region
Andalucía                      16
Aragón                         16
Asturias, Principado de        16
Balears, Illes                 16
Canarias                       16
Cantabria                      16
Castilla - La Mancha           16
Castilla y León                16
Cataluña                       16
Ceuta                          16
Comunitat Valenciana           16
Extremadura                    16
Galicia                        16
Madrid, Comunidad de           16
Melilla                        16
Murcia, Región de              16
Navarra, Comunidad Foral de    16
País Vasco                     16
Rioja, La                      16
Total                          16
dtype: int64

In [29]:
#@title Filtrar por las regiones_deseadas y provincias_deseadas  de nuestro análisis

 # Lista de regiones_deseadas
regiones_deseadas = ['Madrid, Comunidad de', 'Comunitat Valenciana', 'Cataluña','Andalucía', 'Balears, Illes']



# Filtrar el DataFrame para quedarse solo con las filas que contengan las regiones_deseadas
total_turistas = total_turistas[total_turistas['Region'].isin(regiones_deseadas)]
# Filtrar el DataFrame para quedarse solo con las filas que contengan las provincias_deseadas
motivo_viaje = motivo_viaje[motivo_viaje['Region'].isin(regiones_deseadas)]

# Filtrar el DataFrame para quedarse solo con las filas que contengan las regiones_deseadas
via_acceso = via_acceso[via_acceso['Region'].isin(regiones_deseadas)]
# Filtrar el DataFrame para quedarse solo con las filas que contengan las regiones_deseadas
duracion_viaje = duracion_viaje[duracion_viaje['Region'].isin(regiones_deseadas)]

# Filtrar el DataFrame para quedarse solo con las filas que contengan las regiones_deseadas
tipo_alojamiento = tipo_alojamiento[tipo_alojamiento['Region'].isin(regiones_deseadas)]

In [30]:
total_turistas

                   Region             Tipo de dato   Año       Total
16              Andalucía                Dato base  2023  12.200.666
17              Andalucía                Dato base  2022  10.009.890
18              Andalucía                Dato base  2021   4.248.340
19              Andalucía                Dato base  2020   2.700.613
20              Andalucía                Dato base  2019  12.023.153
..                    ...                      ...   ...         ...
219  Madrid, Comunidad de  Tasa de variación anual  2020      -77,51
220  Madrid, Comunidad de  Tasa de variación anual  2019        7,02
221  Madrid, Comunidad de  Tasa de variación anual  2018        6,57
222  Madrid, Comunidad de  Tasa de variación anual  2017       15,85
223  Madrid, Comunidad de  Tasa de variación anual  2016       14,06

[80 rows x 4 columns]

In [31]:

#@title Dividir la columna 'Periodo' en dos nuevas columnas 'Año' y 'Mes'
motivo_viaje[['Año', 'Mes']] = motivo_viaje['Periodo'].str.extract(r'(\d{4})M(\d{2})')
via_acceso[['Año', 'Mes']] = via_acceso['Periodo'].str.extract(r'(\d{4})M(\d{2})')
duracion_viaje[['Año', 'Mes']] = duracion_viaje['Periodo'].str.extract(r'(\d{4})M(\d{2})')
tipo_alojamiento[['Año', 'Mes']] = tipo_alojamiento['Periodo'].str.extract(r'(\d{4})M(\d{2})')

In [32]:
motivo_viaje

,Region,Motivo del viaje,Periodo,Total,Año,Mes
0,Andalucía,Negocios y otros motivos profesionales,2019M12,84140.0,2019,12
1,Andalucía,Negocios y otros motivos profesionales,2019M11,64505.0,2019,11
2,Andalucía,Negocios y otros motivos profesionales,2019M10,73955.0,2019,10
3,Andalucía,Negocios y otros motivos profesionales,2019M09,86912.0,2019,09
4,Andalucía,Negocios y otros motivos profesionales,2019M08,20461.0,2019,08
...,...,...,...,...,...,...
1195,"Madrid, Comunidad de",Total de motivos del viaje,2023M05,704007.0,2023,05
1196,"Madrid, Comunidad de",Total de motivos del viaje,2023M04,665430.0,2023,04
1197,"Madrid, Comunidad de",Total de motivos del viaje,2023M03,594387.0,2023,03
1198,"Madrid, Comunidad de",Total de motivos del viaje,2023M02,453469.0,2023,02
1199,"Madrid, Comunidad de",Total de motivos del viaje,2023M01,528543.0,2023,01

In [33]:
#@title Filtrar por la columna año >= 2019 y convertir a número

# Convertir la columna 'Año' a int y luego filtrar por año >= 2019
total_turistas['Año'] = total_turistas['Año'].astype(int)
total_turistas = total_turistas[total_turistas['Año'] >= 2019]

motivo_viaje['Año'] = motivo_viaje['Año'].astype(int)
motivo_viaje = motivo_viaje[motivo_viaje['Año'] >= 2019]

duracion_viaje['Año'] = duracion_viaje['Año'].astype(int)
duracion_viaje = duracion_viaje[duracion_viaje['Año'] >= 2019]

tipo_alojamiento['Año'] = tipo_alojamiento['Año'].astype(int)
tipo_alojamiento = tipo_alojamiento[tipo_alojamiento['Año'] >= 2019]

via_acceso['Año'] = via_acceso['Año'].astype(int)
via_acceso = via_acceso[via_acceso['Año'] >= 2019]

In [34]:
#@title Eliminar la columna Periodo de cada DataFrame

# Eliminar la columna 'Periodo' de cada DataFrame
try:
    motivo_viaje.drop('Periodo', axis=1, inplace=True)
except KeyError:
    print("La columna 'Periodo' no se encuentra en motivo_viaje.")
try:
    duracion_viaje.drop('Periodo', axis=1, inplace=True)
except KeyError:
    print("La columna 'Periodo' no se encuentra en duracion_viaje.")
try:
    via_acceso.drop('Periodo', axis=1, inplace=True)
except KeyError:
    print("La columna 'Periodo' no se encuentra en via_acceso.")


try:
    tipo_alojamiento.drop('Periodo', axis=1, inplace=True)
except KeyError:
    print("La columna 'Periodo' no se encuentra en tipo_alojamiento.")

In [35]:
#@title Eliminar la columna MEs de cada DataFrame

# Eliminar la columna 'Mes' de cada DataFrame
try:
    motivo_viaje.drop('Mes', axis=1, inplace=True)
except KeyError:
    print("La columna ''Mes' no se encuentra en motivo_viaje.")
try:
    duracion_viaje.drop('Mes', axis=1, inplace=True)
except KeyError:
    print("La columna 'Mes' no se encuentra en duracion_viaje.")
try:
    via_acceso.drop('Mes', axis=1, inplace=True)
except KeyError:
    print("La columna 'Mes' no se encuentra en via_acceso.")

try:
    tipo_alojamiento.drop('Mes', axis=1, inplace=True)
except KeyError:
    print("La columna 'Mes' no se encuentra en tipo_alojamiento.")

In [36]:
#@title Verificar las columnas de los csv


print("Columnas en total_turistas:")
print(total_turistas.columns)

print("\nColumnas en motivo_viaje:")
print(motivo_viaje.columns)

print("\nColumnas en tipo_alojamiento:")
print(tipo_alojamiento.columns)

print("\nColumnas en via_acceso:")
print(via_acceso.columns)

print("\nColumnas en duracion_viaje:")
print(duracion_viaje.columns)

Columnas en total_turistas:
Index(['Region', 'Tipo de dato', 'Año', 'Total'], dtype='object')

Columnas en motivo_viaje:
Index(['Region', 'Motivo del viaje', 'Total', 'Año'], dtype='object')

Columnas en tipo_alojamiento:
Index(['Region', 'Tipo de alojamiento', 'Total', 'Año'], dtype='object')

Columnas en via_acceso:
Index(['Vía de acceso', 'Region', 'Total', 'Año'], dtype='object')

Columnas en duracion_viaje:
Index(['Region', 'Duración del viaje', 'Total', 'Año'], dtype='object')

In [37]:
#@title Verificar los valores nulos

# total_turistas
nulos_total_turistas = total_turistas.isnull().sum()

#motivo_viaje
nulos_motivo_viaje = motivo_viaje.isnull().sum()

#tipo_alojamiento
nulo_tipo_alojamiento = tipo_alojamiento.isnull().sum()


#dvia_acceso
nulo_via_acceso = via_acceso.isnull().sum()

#duracion_viaje
nulo_duracion_viaje = duracion_viaje.isnull().sum()


# Imprimir los resultados
print("Valores nulos en total_turistas:\n", nulos_total_turistas)
print("\nValores nulos en motivo_viaje:\n", nulos_motivo_viaje)
print("\nValores nulos en tipo_alojamiento:\n", nulo_tipo_alojamiento)
print("\nValores nulos en nulo_via_acceso:\n", nulo_via_acceso)
print("\nValores nulos en duracion_viaje:\n", nulo_duracion_viaje)

Valores nulos en total_turistas:
 Region          0
Tipo de dato    0
Año             0
Total           0
dtype: int64

Valores nulos en motivo_viaje:
 Region               0
Motivo del viaje     0
Total               50
Año                  0
dtype: int64

Valores nulos en tipo_alojamiento:
 Region                   0
Tipo de alojamiento      0
Total                  509
Año                      0
dtype: int64

Valores nulos en nulo_via_acceso:
 Vía de acceso      0
Region             0
Total            467
Año                0
dtype: int64

Valores nulos en duracion_viaje:
 Region                  0
Duración del viaje      0
Total                 171
Año                     0
dtype: int64

In [38]:
#@title Eliminar los valores nulos

motivo_viaje = motivo_viaje.dropna(subset=['Total'])
via_acceso = via_acceso.dropna(subset=['Total'])
duracion_viaje = duracion_viaje.dropna(subset=['Total'])
tipo_alojamiento = tipo_alojamiento.dropna(subset=['Total'])

In [39]:
#@title Ordenar los datos por las columnas correspondientes

total_turistas = total_turistas[['Año', 'Region', 'Tipo de dato', 'Total']]

motivo_viaje = motivo_viaje[[
     'Año', 'Region', 'Motivo del viaje','Total'
]]
via_acceso = via_acceso[[
     'Año', 'Region', 'Vía de acceso','Total'
]]
duracion_viaje = duracion_viaje[[
     'Año', 'Region', 'Duración del viaje','Total'
]]
tipo_alojamiento = tipo_alojamiento[[
     'Año', 'Region', 'Tipo de alojamiento','Total'
]]

In [40]:
#@title Verificar las columnas de los csv


print("Columnas en total_turistas:")
print(total_turistas.columns)

print("\nColumnas en motivo_viaje:")
print(motivo_viaje.columns)

print("\nColumnas en tipo_alojamiento:")
print(tipo_alojamiento.columns)

print("\nColumnas en via_acceso:")
print(via_acceso.columns)

print("\nColumnas en duracion_viaje:")
print(duracion_viaje.columns)

Columnas en total_turistas:
Index(['Año', 'Region', 'Tipo de dato', 'Total'], dtype='object')

Columnas en motivo_viaje:
Index(['Año', 'Region', 'Motivo del viaje', 'Total'], dtype='object')

Columnas en tipo_alojamiento:
Index(['Año', 'Region', 'Tipo de alojamiento', 'Total'], dtype='object')

Columnas en via_acceso:
Index(['Año', 'Region', 'Vía de acceso', 'Total'], dtype='object')

Columnas en duracion_viaje:
Index(['Año', 'Region', 'Duración del viaje', 'Total'], dtype='object')

In [41]:
#@title Crear la tabla dinámica para Total Turistas

# Convertir la columna "Total" a numérico, asumiendo que los datos ya están en el DataFrame `total_turistas`
total_turistas['Total'] = pd.to_numeric(total_turistas['Total'].str.replace('.', '').str.replace(',', '.'), errors='coerce')

# Primero, filtramos para cada tipo y creamos las columnas correspondientes.

df_turistas = total_turistas[total_turistas['Tipo de dato'] == 'Dato base']

df_tasa_variacion = total_turistas[total_turistas['Tipo de dato'] == 'Tasa de variación anual']


# Ahora, creamos la tabla dinámica para cada tipo.

pivot_turistas = df_turistas.pivot_table(index=['Año', 'Region'],
                                           values='Total',
                                           aggfunc='sum').rename(columns={'Total': 'num_turistas'})

pivot_tasa_variacion = df_tasa_variacion.pivot_table(index=['Año', 'Region'],
                                           values='Total',
                                           aggfunc='sum').rename(columns={'Total': 'tasa_variacion'})


# Unimos las cuatro tablas dinámicas en una sola DataFrame final#usamos pd.concat al combinar varias tablas
df_total_turistas   = pd.concat([
    pivot_turistas, pivot_tasa_variacion,
], axis=1).reset_index()


# Redondear la columna 'df_total_turistas' a dos decimales
df_total_turistas['num_turistas'] = df_total_turistas['num_turistas'].round(2)

df_total_turistas['tasa_variacion'] = df_total_turistas['tasa_variacion'].round(2)


df_total_turistas

     Año                Region  num_turistas  tasa_variacion
0   2019             Andalucía    12023153.0            2.93
1   2019        Balears, Illes    13679781.0           -1.24
2   2019              Cataluña    19375152.0            0.93
3   2019  Comunitat Valenciana     9535496.0            3.57
4   2019  Madrid, Comunidad de     7640980.0            7.02
5   2020             Andalucía     2700613.0          -77.54
6   2020        Balears, Illes     1721123.0          -87.42
7   2020              Cataluña     3870259.0          -80.02
8   2020  Comunitat Valenciana     2542758.0          -73.33
9   2020  Madrid, Comunidad de     1718335.0          -77.51
10  2021             Andalucía     4248340.0           57.31
11  2021        Balears, Illes     6324711.0          267.48
12  2021              Cataluña     5787837.0           49.55
13  2021  Comunitat Valenciana     4019766.0           58.09
14  2021  Madrid, Comunidad de     2177068.0           26.70
15  2022             Andalucía    10009890.0          135.62
16  2022        Balears, Illes    13203885.0          108.77
17  2022              Cataluña    14852042.0          156.61
18  2022  Comunitat Valenciana     8616445.0          114.35
19  2022  Madrid, Comunidad de     6048182.0          177.81
20  2023             Andalucía    12200666.0           21.89
21  2023        Balears, Illes    14405322.0            9.10
22  2023              Cataluña    18004010.0           21.22
23  2023  Comunitat Valenciana    10491985.0           21.77
24  2023  Madrid, Comunidad de     7841055.0           29.64

In [42]:
#@title Crear la tabla dinámica para motivo_viaje

# Convertir la columna "Total" a numérico, manejando correctamente los separadores
# motivo_viaje['Total'] = pd.to_numeric(motivo_viaje['Total'].str.replace('.', '').str.replace(',', '.'), errors='coerce')

# No necesitamos filtrar por "Tipo de dato" ya que trabajaremos directamente con los motivos

# Crear tablas dinámicas para cada motivo del viaje
pivot_negocios = motivo_viaje[motivo_viaje['Motivo del viaje'] == 'Negocios y otros motivos profesionales'].pivot_table(index=['Año', 'Region'],
                                                                                                                         values='Total',
                                                                                                                         aggfunc='sum').rename(columns={'Total': 'total_negocios'})

pivot_ocio = motivo_viaje[motivo_viaje['Motivo del viaje'] == 'Ocio, recreo y vacaciones'].pivot_table(index=['Año', 'Region'],
                                                                                                       values='Total',
                                                                                                       aggfunc='sum').rename(columns={'Total': 'total_ocio'})

pivot_otros = motivo_viaje[motivo_viaje['Motivo del viaje'] == 'Otros motivos'].pivot_table(index=['Año', 'Region'],
                                                                                             values='Total',
                                                                                             aggfunc='sum').rename(columns={'Total': 'total_otros'})

# Unimos las tablas dinámicas en un solo DataFrame final
df_motivo_viaje = pd.concat([pivot_negocios, pivot_ocio, pivot_otros], axis=1).reset_index()

# Redondear las columnas a dos decimales
df_motivo_viaje['total_negocios'] = df_motivo_viaje['total_negocios'].round(2)
df_motivo_viaje['total_ocio'] = df_motivo_viaje['total_ocio'].round(2)
df_motivo_viaje['total_otros'] = df_motivo_viaje['total_otros'].round(2)

df_motivo_viaje

     Año                Region  total_negocios  total_ocio  total_otros
0   2019             Andalucía        814791.0  10337528.0     870833.0
1   2019        Balears, Illes        315654.0  13112902.0     235666.0
2   2019              Cataluña       1611272.0  16552222.0    1211658.0
3   2019  Comunitat Valenciana        499142.0   8302532.0     733821.0
4   2019  Madrid, Comunidad de       1147620.0   5897843.0     595518.0
5   2020             Andalucía        221744.0   2132928.0     341641.0
6   2020        Balears, Illes         48620.0   1574007.0      93621.0
7   2020              Cataluña        327546.0   3126727.0     413718.0
8   2020  Comunitat Valenciana        156225.0   2106692.0     278582.0
9   2020  Madrid, Comunidad de        264020.0   1278964.0     173703.0
10  2021             Andalucía        333151.0   3432951.0     482240.0
11  2021        Balears, Illes        130717.0   6015788.0     178208.0
12  2021              Cataluña        469502.0   4803352.0     514982.0
13  2021  Comunitat Valenciana        223425.0   3307490.0     488851.0
14  2021  Madrid, Comunidad de        382481.0   1490424.0     304161.0
15  2022             Andalucía        551621.0   8541398.0     916873.0
16  2022        Balears, Illes        260808.0  12589615.0     319546.0
17  2022              Cataluña       1310356.0  12645493.0     896193.0
18  2022  Comunitat Valenciana        435961.0   7243948.0     936536.0
19  2022  Madrid, Comunidad de        834561.0   4597717.0     615908.0
20  2023             Andalucía        667946.0  10639710.0     893010.0
21  2023        Balears, Illes        315009.0  13667232.0     423083.0
22  2023              Cataluña       1258943.0  15432643.0    1312423.0
23  2023  Comunitat Valenciana        391417.0   8900511.0    1200053.0
24  2023  Madrid, Comunidad de       1096993.0   5819038.0     925024.0

In [43]:
#@title Crear la tabla dinámica para via_acceso:

# Convertir la columna "Total" a numérico, si aún no se ha hecho
via_acceso['Total'] = pd.to_numeric(via_acceso['Total'].str.replace('.', '').str.replace(',', '.'), errors='coerce')

# Crear tablas dinámicas para cada tipo de vía de acceso
pivot_aeropuerto = via_acceso[via_acceso['Vía de acceso'] == 'Aeropuerto'].pivot_table(index=['Año', 'Region'],
                                                                                       values='Total',
                                                                                       aggfunc='sum').rename(columns={'Total': 'total_aeropuerto'})

pivot_carretera = via_acceso[via_acceso['Vía de acceso'] == 'Carretera'].pivot_table(index=['Año', 'Region'],
                                                                                     values='Total',
                                                                                     aggfunc='sum').rename(columns={'Total': 'total_carretera'})

pivot_puerto = via_acceso[via_acceso['Vía de acceso'] == 'Puerto'].pivot_table(index=['Año', 'Region'],
                                                                               values='Total',
                                                                               aggfunc='sum').rename(columns={'Total': 'total_puerto'})

pivot_tren = via_acceso[via_acceso['Vía de acceso'] == 'Tren'].pivot_table(index=['Año', 'Region'],
                                                                           values='Total',
                                                                           aggfunc='sum').rename(columns={'Total': 'total_tren'})

# No necesitamos crear una tabla dinámica para "Total de vías de acceso" ya que es un agregado de los otros

# Unimos las tablas dinámicas en un solo DataFrame final
df_via_acceso = pd.concat([pivot_aeropuerto, pivot_carretera, pivot_puerto, pivot_tren], axis=1).reset_index()

# Redondear las columnas a dos decimales, si es necesario
df_via_acceso = df_via_acceso.round(2)

df_via_acceso

,Año,Region,total_aeropuerto,total_carretera,total_puerto,total_tren
0,2019,Andalucía,9768879,1652276.0,593317.0,NaN
1,2019,"Balears, Illes",13606365,NaN,NaN,NaN
2,2019,Cataluña,14044000,4324389.0,756276.0,250486.0
3,2019,Comunitat Valenciana,7582134,1786095.0,156546.0,4149.0
4,2019,"Madrid, Comunidad de",7103209,55468.0,3491.0,42690.0
5,2020,Andalucía,2051050,517748.0,88911.0,NaN
6,2020,"Balears, Illes",1696038,NaN,NaN,NaN
7,2020,Cataluña,2075138,1675634.0,46492.0,66275.0
8,2020,Comunitat Valenciana,1752375,703509.0,36156.0,565.0
9,2020,"Madrid, Comunidad de",1558486,NaN,NaN,14883.0
10,2021,Andalucía,3622366,567077.0,27115.0,NaN
11,2021,"Balears, Illes",6286255,NaN,NaN,NaN
12,2021,Cataluña,3341756,2221700.0,117066.0,104963.0
13,2021,Comunitat Valenciana,2875743,1072121.0,28047.0,NaN
14,2021,"Madrid, Comunidad de",2020142,NaN,NaN,18217.0
15,2022,Andalucía,8590630,1201573.0,208901.0,2005.0
16,2022,"Balears, Illes",13117255,NaN,NaN,NaN
17,2022,Cataluña,10315029,3761574.0,600853.0,174587.0
18,2022,Comunitat Valenciana,6650744,1845617.0,110697.0,2949.0
19,2022,"Madrid, Comunidad de",5699566,NaN,23379.0,21255.0
20,2023,Andalucía,10209599,1562120.0,415466.0,NaN
21,2023,"Balears, Illes",14190588,NaN,122590.0,NaN
22,2023,Cataluña,12431521,4480922.0,852374.0,239193.0
23,2023,Comunitat Valenciana,8039988,2294686.0,144805.0,4965.0
24,2023,"Madrid, Comunidad de",7407795,NaN,41246.0,32641.0

In [44]:

#@title Crear la tabla dinámica para duracion_viaje

# Convertir la columna "Total" a numérico, manejando correctamente los separadores
duracion_viaje['Total'] = pd.to_numeric(duracion_viaje['Total'].str.replace('.', '').str.replace(',', '.'), errors='coerce')

# Crear tablas dinámicas para cada categoría de duración del viaje
pivot_1_noche = duracion_viaje[duracion_viaje['Duración del viaje'] == '1 noche'].pivot_table(index=['Año', 'Region'],
                                                                                             values='Total',
                                                                                             aggfunc='sum').rename(columns={'Total': 'total_1_noche'})

pivot_2_3_noches = duracion_viaje[duracion_viaje['Duración del viaje'] == 'De 2 a 3 noches'].pivot_table(index=['Año', 'Region'],
                                                                                                       values='Total',
                                                                                                       aggfunc='sum').rename(columns={'Total': 'total_2_3_noches'})

pivot_4_7_noches = duracion_viaje[duracion_viaje['Duración del viaje'] == 'De 4 a 7 noches'].pivot_table(index=['Año', 'Region'],
                                                                                                       values='Total',
                                                                                                       aggfunc='sum').rename(columns={'Total': 'total_4_7_noches'})

pivot_8_15_noches = duracion_viaje[duracion_viaje['Duración del viaje'] == 'De 8 a 15 noches'].pivot_table(index=['Año', 'Region'],
                                                                                                         values='Total',
                                                                                                         aggfunc='sum').rename(columns={'Total': 'total_8_15_noches'})

pivot_mas_15_noches = duracion_viaje[duracion_viaje['Duración del viaje'] == 'Más de 15 noches'].pivot_table(index=['Año', 'Region'],
                                                                                                           values='Total',
                                                                                                           aggfunc='sum').rename(columns={'Total': 'total_mas_15_noches'})

# Unimos las tablas dinámicas en un solo DataFrame final
df_duracion_viaje = pd.concat([pivot_1_noche, pivot_2_3_noches, pivot_4_7_noches, pivot_8_15_noches, pivot_mas_15_noches], axis=1).reset_index()

# Redondear las columnas a dos decimales
df_duracion_viaje['total_1_noche'] = df_duracion_viaje['total_1_noche'].round(2)
df_duracion_viaje['total_2_3_noches'] = df_duracion_viaje['total_2_3_noches'].round(2)
df_duracion_viaje['total_4_7_noches'] = df_duracion_viaje['total_4_7_noches'].round(2)
df_duracion_viaje['total_8_15_noches'] = df_duracion_viaje['total_8_15_noches'].round(2)
df_duracion_viaje['total_mas_15_noches'] = df_duracion_viaje['total_mas_15_noches'].round(2)

df_duracion_viaje

,Año,Region,total_1_noche,total_2_3_noches,total_4_7_noches,total_8_15_noches,total_mas_15_noches
0,2019,Andalucía,420715.0,2009347,5737517,2882991,972583
1,2019,"Balears, Illes",10237.0,1723273,8231339,3245504,383976
2,2019,Cataluña,1415553.0,5297229,8610923,3258175,793274
3,2019,Comunitat Valenciana,151719.0,1654085,3980770,2534482,1197089
4,2019,"Madrid, Comunidad de",620274.0,2470449,2948450,1122835,478968
5,2020,Andalucía,34312.0,439945,1209888,615979,354178
6,2020,Cataluña,368232.0,1053962,1640406,568311,232862
7,2020,Comunitat Valenciana,22099.0,383237,958995,694442,457186
8,2020,"Madrid, Comunidad de",152348.0,567767,615457,245734,130351
9,2021,Andalucía,13165.0,536685,1850727,1229630,533965
10,2021,Cataluña,398445.0,1549206,2516018,979204,344963
11,2021,Comunitat Valenciana,16755.0,452031,1482058,1261135,759250
12,2021,"Madrid, Comunidad de",231757.0,622932,791617,357875,172887
13,2022,Andalucía,211311.0,1839884,4512708,2476990,911922
14,2022,Cataluña,1035671.0,4159136,7071205,1981267,604765
15,2022,Comunitat Valenciana,107584.0,1280132,3669513,2306167,1219890
16,2022,"Madrid, Comunidad de",533854.0,1918373,2235417,883752,476786
17,2023,Andalucía,332491.0,2152735,5595301,3016497,1082797
18,2023,"Balears, Illes",104469.0,1791895,8677294,3341621,443287
19,2023,Cataluña,1332590.0,5247467,8378727,2338551,706676
20,2023,Comunitat Valenciana,86275.0,1547693,4669847,2732653,1378312
21,2023,"Madrid, Comunidad de",623316.0,2360427,3032604,1166033,658675
22,2020,"Balears, Illes",NaN,164675,911726,494145,134398
23,2021,"Balears, Illes",NaN,512647,3562733,1901379,316028
24,2022,"Balears, Illes",NaN,1647137,7867678,3202364,405168

In [45]:
#@title Crear la tabla dinámica para tipo_alojamiento


# Convertir la columna "Total" a numérico, si aún no se ha hecho
tipo_alojamiento['Total'] = pd.to_numeric(tipo_alojamiento['Total'].str.replace('.', '').str.replace(',', '.'), errors='coerce')

# Crear tablas dinámicas para cada tipo de alojamiento
pivot_de_mercado = tipo_alojamiento[tipo_alojamiento['Tipo de alojamiento'] == 'De mercado'].pivot_table(index=['Año', 'Region'],
                                                                                                        values='Total',
                                                                                                        aggfunc='sum').rename(columns={'Total': 'total_de_mercado'})

pivot_hotelero = tipo_alojamiento[tipo_alojamiento['Tipo de alojamiento'] == 'Hotelero'].pivot_table(index=['Año', 'Region'],
                                                                                                     values='Total',
                                                                                                     aggfunc='sum').rename(columns={'Total': 'total_hotelero'})

pivot_no_de_mercado = tipo_alojamiento[tipo_alojamiento['Tipo de alojamiento'] == 'No de mercado'].pivot_table(index=['Año', 'Region'],
                                                                                                               values='Total',
                                                                                                               aggfunc='sum').rename(columns={'Total': 'total_no_de_mercado'})

pivot_resto_de_mercado = tipo_alojamiento[tipo_alojamiento['Tipo de alojamiento'] == 'Resto de mercado'].pivot_table(index=['Año', 'Region'],
                                                                                                                      values='Total',
                                                                                                                      aggfunc='sum').rename(columns={'Total': 'total_resto_de_mercado'})

pivot_resto_de_no_mercado = tipo_alojamiento[tipo_alojamiento['Tipo de alojamiento'] == 'Resto de no mercado'].pivot_table(index=['Año', 'Region'],
                                                                                                                            values='Total',
                                                                                                                            aggfunc='sum').rename(columns={'Total': 'total_resto_de_no_mercado'})

pivot_vivienda_familiares_amigos = tipo_alojamiento[tipo_alojamiento['Tipo de alojamiento'] == 'Vivienda de familiares o amigos'].pivot_table(index=['Año', 'Region'],
                                                                                                                                             values='Total',
                                                                                                                                             aggfunc='sum').rename(columns={'Total': 'total_vivienda_familiares_amigos'})

pivot_vivienda_alquiler = tipo_alojamiento[tipo_alojamiento['Tipo de alojamiento'] == 'Vivienda en alquiler'].pivot_table(index=['Año', 'Region'],
                                                                                                                           values='Total',
                                                                                                                           aggfunc='sum').rename(columns={'Total': 'total_vivienda_alquiler'})

pivot_vivienda_propiedad = tipo_alojamiento[tipo_alojamiento['Tipo de alojamiento'] == 'Vivienda en propiedad'].pivot_table(index=['Año', 'Region'],
                                                                                                                             values='Total',
                                                                                                                             aggfunc='sum').rename(columns={'Total': 'total_vivienda_propiedad'})

# Unimos las tablas dinámicas en un solo DataFrame final
df_tipo_alojamiento= pd.concat([pivot_de_mercado, pivot_hotelero, pivot_no_de_mercado, pivot_resto_de_mercado, pivot_resto_de_no_mercado,
                                       pivot_vivienda_familiares_amigos, pivot_vivienda_alquiler, pivot_vivienda_propiedad], axis=1).reset_index()

# Redondear las columnas a dos decimales, si es necesario
df_tipo_alojamiento_ = df_tipo_alojamiento.round(2)

df_tipo_alojamiento

,Año,Region,total_de_mercado,total_hotelero,total_no_de_mercado,total_resto_de_mercado,total_resto_de_no_mercado,total_vivienda_familiares_amigos,total_vivienda_alquiler,total_vivienda_propiedad
0,2019,Andalucía,9673391,7527124,2349763,347452.0,130621.0,1181125,1798814,1001327.0
1,2019,"Balears, Illes",12030848,10054071,1648934,239448.0,6783.0,879908,1719815,708039.0
2,2019,Cataluña,16711029,13297031,2664124,1542155.0,36759.0,1913463,1871843,614374.0
3,2019,Comunitat Valenciana,5787400,3970791,3748095,237675.0,5892.0,2130818,1567144,1542956.0
4,2019,"Madrid, Comunidad de",6269290,5521046,1371691,NaN,7298.0,1243656,683624,16765.0
5,2020,Andalucía,2078323,1543227,622289,45463.0,16678.0,321621,418285,269200.0
6,2020,"Balears, Illes",1205523,881533,515602,30823.0,2657.0,245357,286417,254867.0
7,2020,Cataluña,2987064,2324588,883193,274555.0,10642.0,605921,387921,212583.0
8,2020,Comunitat Valenciana,1389039,935714,1153719,59085.0,NaN,605645,363084,529032.0
9,2020,"Madrid, Comunidad de",1333364,1129836,384973,NaN,NaN,353960,184683,NaN
10,2021,Andalucía,3250719,2538761,997623,62695.0,16538.0,545050,605741,406300.0
11,2021,"Balears, Illes",5204188,4103201,1120522,89741.0,8779.0,503644,1002442,578694.0
12,2021,Cataluña,5021481,4229749,766355,484050.0,1927.0,535177,303912,202944.0
13,2021,Comunitat Valenciana,2193646,1548118,1826123,106371.0,NaN,951473,526191,858127.0
14,2021,"Madrid, Comunidad de",1850338,1745357,326728,NaN,NaN,300069,94853,509.0
15,2022,Andalucía,8146730,6317803,1863161,193780.0,35660.0,1007862,1610340,755550.0
16,2022,"Balears, Illes",11537484,9754269,1666400,379357.0,12975.0,796387,1400028,791223.0
17,2022,Cataluña,13217537,11232383,1634504,1015527.0,17233.0,1216781,969626,351221.0
18,2022,Comunitat Valenciana,5173988,3613206,3442457,181218.0,NaN,1819431,1360092,1568226.0
19,2022,"Madrid, Comunidad de",4929755,4371528,1118426,NaN,NaN,1045528,509412,NaN
20,2023,Andalucía,9880937,7645213,2319730,326781.0,64927.0,1249529,1908941,959143.0
21,2023,"Balears, Illes",12605047,10698434,1800274,370925.0,32892.0,932035,1512908,771725.0
22,2023,Cataluña,15426684,12497395,2577327,978530.0,43073.0,1903015,1950759,513597.0
23,2023,Comunitat Valenciana,6088290,4049226,4403693,205397.0,23480.0,2391285,1791949,1889415.0
24,2023,"Madrid, Comunidad de",6374500,5566603,1466557,NaN,21218.0,1322346,750761,NaN

In [52]:

#@title Renombrar las columnas dde los dataframes en ingles

df_total_turistas = df_total_turistas.rename(columns={
    'Año':'Year',
    'num_turistas': 'NumberOfTourists',
    'tasa_variacion': 'VariationRate'
})



df_motivo_viaje = df_motivo_viaje.rename(columns={
     'Año':'Year',
    'total_negocios': 'Business',
    'total_ocio': 'Leisure',
    'total_otros': 'Other',
})


df_duracion_viaje = df_duracion_viaje.rename(columns={
    'Año':'Year',
    'total_1_noche': '1Night',
    'total_2_3_noches': '2To3Nights',
    'total_4_7_noches': '4To7Nights',
    'total_8_15_noches': '8To15Nights',
    'total_mas_15_noches': '>15Nights',
})

df_via_acceso = df_via_acceso.rename(columns={
    'Año':'Year',
    'total_aeropuerto': 'airport',
    'total_carretera': 'road',
    'total_puerto': 'port',
    'total_tren': 'train'
})


df_tipo_alojamiento = df_tipo_alojamiento.rename(columns={
    'Año':'Year',
    'total_de_mercado': 'Market',
    'total_hotelero': 'Hotel',
    'total_no_de_mercado': 'NonMarket',
    'total_resto_de_mercado': 'OtherMarket',
    'total_resto_de_no_mercado': 'OtherNonMarket',
    'total_vivienda_familiares_amigos': 'HousingRelativesFriends',
    'total_vivienda_alquiler': 'RentalHousing',
    'total_vivienda_propiedad': 'OwnedHousing'
})

In [53]:
df_total_turistas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              25 non-null     int64
 1   Region            25 non-null     object
 2   NumberOfTourists  25 non-null     float64
 3   VariationRate     25 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 928.0+ bytes

In [54]:
df_tipo_alojamiento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year                     25 non-null     int64
 1   Region                   25 non-null     object
 2   Market                   25 non-null     int64
 3   Hotel                    25 non-null     int64
 4   NonMarket                25 non-null     int64
 5   OtherMarket              20 non-null     float64
 6   OtherNonMarket           19 non-null     float64
 7   HousingRelativesFriends  25 non-null     int64
 8   RentalHousing            25 non-null     int64
 9   OwnedHousing             22 non-null     float64
dtypes: float64(3), int64(6), object(1)
memory usage: 2.1+ KB

In [56]:
#@title Uniendo las tablas

# Primero combinamos df_total_turistas con df_motivo_viaje
df_combinado_1 = pd.merge(df_total_turistas, df_motivo_viaje, on=['Year', 'Region'], how='outer')

# Luego combinamos el resultado con df_duracion_viaje
df_combinado_2 = pd.merge(df_combinado_1, df_duracion_viaje, on=['Year', 'Region'], how='outer')

# Y así sucesivamente con los demás DataFrames
df_combinado_3 = pd.merge(df_combinado_2, df_via_acceso, on=['Year', 'Region'], how='outer')
df_final = pd.merge(df_combinado_3, df_tipo_alojamiento, on=['Year', 'Region'], how='outer')

In [57]:
df_final

,Year,Region,NumberOfTourists,VariationRate,Business,Leisure,Other,1Night,2To3Nights,4To7Nights,...,port,train,Market,Hotel,NonMarket,OtherMarket,OtherNonMarket,HousingRelativesFriends,RentalHousing,OwnedHousing
0,2019,Andalucía,12023153.0,2.93,814791.0,10337528.0,870833.0,420715.0,2009347,5737517,...,593317.0,NaN,9673391,7527124,2349763,347452.0,130621.0,1181125,1798814,1001327.0
1,2019,"Balears, Illes",13679781.0,-1.24,315654.0,13112902.0,235666.0,10237.0,1723273,8231339,...,NaN,NaN,12030848,10054071,1648934,239448.0,6783.0,879908,1719815,708039.0
2,2019,Cataluña,19375152.0,0.93,1611272.0,16552222.0,1211658.0,1415553.0,5297229,8610923,...,756276.0,250486.0,16711029,13297031,2664124,1542155.0,36759.0,1913463,1871843,614374.0
3,2019,Comunitat Valenciana,9535496.0,3.57,499142.0,8302532.0,733821.0,151719.0,1654085,3980770,...,156546.0,4149.0,5787400,3970791,3748095,237675.0,5892.0,2130818,1567144,1542956.0
4,2019,"Madrid, Comunidad de",7640980.0,7.02,1147620.0,5897843.0,595518.0,620274.0,2470449,2948450,...,3491.0,42690.0,6269290,5521046,1371691,NaN,7298.0,1243656,683624,16765.0
5,2020,Andalucía,2700613.0,-77.54,221744.0,2132928.0,341641.0,34312.0,439945,1209888,...,88911.0,NaN,2078323,1543227,622289,45463.0,16678.0,321621,418285,269200.0
6,2020,"Balears, Illes",1721123.0,-87.42,48620.0,1574007.0,93621.0,NaN,164675,911726,...,NaN,NaN,1205523,881533,515602,30823.0,2657.0,245357,286417,254867.0
7,2020,Cataluña,3870259.0,-80.02,327546.0,3126727.0,413718.0,368232.0,1053962,1640406,...,46492.0,66275.0,2987064,2324588,883193,274555.0,10642.0,605921,387921,212583.0
8,2020,Comunitat Valenciana,2542758.0,-73.33,156225.0,2106692.0,278582.0,22099.0,383237,958995,...,36156.0,565.0,1389039,935714,1153719,59085.0,NaN,605645,363084,529032.0
9,2020,"Madrid, Comunidad de",1718335.0,-77.51,264020.0,1278964.0,173703.0,152348.0,567767,615457,...,NaN,14883.0,1333364,1129836,384973,NaN,NaN,353960,184683,NaN
10,2021,Andalucía,4248340.0,57.31,333151.0,3432951.0,482240.0,13165.0,536685,1850727,...,27115.0,NaN,3250719,2538761,997623,62695.0,16538.0,545050,605741,406300.0
11,2021,"Balears, Illes",6324711.0,267.48,130717.0,6015788.0,178208.0,NaN,512647,3562733,...,NaN,NaN,5204188,4103201,1120522,89741.0,8779.0,503644,1002442,578694.0
12,2021,Cataluña,5787837.0,49.55,469502.0,4803352.0,514982.0,398445.0,1549206,2516018,...,117066.0,104963.0,5021481,4229749,766355,484050.0,1927.0,535177,303912,202944.0
13,2021,Comunitat Valenciana,4019766.0,58.09,223425.0,3307490.0,488851.0,16755.0,452031,1482058,...,28047.0,NaN,2193646,1548118,1826123,106371.0,NaN,951473,526191,858127.0
14,2021,"Madrid, Comunidad de",2177068.0,26.70,382481.0,1490424.0,304161.0,231757.0,622932,791617,...,NaN,18217.0,1850338,1745357,326728,NaN,NaN,300069,94853,509.0
15,2022,Andalucía,10009890.0,135.62,551621.0,8541398.0,916873.0,211311.0,1839884,4512708,...,208901.0,2005.0,8146730,6317803,1863161,193780.0,35660.0,1007862,1610340,755550.0
16,2022,"Balears, Illes",13203885.0,108.77,260808.0,12589615.0,319546.0,NaN,1647137,7867678,...,NaN,NaN,11537484,9754269,1666400,379357.0,12975.0,796387,1400028,791223.0
17,2022,Cataluña,14852042.0,156.61,1310356.0,12645493.0,896193.0,1035671.0,4159136,7071205,...,600853.0,174587.0,13217537,11232383,1634504,1015527.0,17233.0,1216781,969626,351221.0
18,2022,Comunitat Valenciana,8616445.0,114.35,435961.0,7243948.0,936536.0,107584.0,1280132,3669513,...,110697.0,2949.0,5173988,3613206,3442457,181218.0,NaN,1819431,1360092,1568226.0
19,2022,"Madrid, Comunidad de",6048182.0,177.81,834561.0,4597717.0,615908.0,533854.0,1918373,2235417,...,23379.0,21255.0,4929755,4371528,1118426,NaN,NaN,1045528,509412,NaN
20,2023,Andalucía,12200666.0,21.89,667946.0,10639710.0,893010.0,332491.0,2152735,5595301,...,415466.0,NaN,9880937,7645213,2319730,326781.0,64927.0,1249529,1908941,959143.0
21,2023,"Balears, Illes",14405322.0,9.10,315009.0,13667232.0,423083.0,104469.0,1791895,8677294,...,122590.0,NaN,12605047,10698434,1800274,370925.0,32892.0,932035,1512908,771725.0
22,2023,Cataluña,18004010.0,21.22,1258943.0,15432643.0,1312423.0,1332590.0,5247467,8378727,...,852374.0,239193.0,15426684,12497395,2577327,978530.0,43073.0,1903015,1950759,513597.0
23,2023,Comunitat Valenciana,10491985.0,21.77,391417.0,8900511.0,1200053.0,86275.0,1547693,4669847,...,144805.0,4965.0,6088290,4049226,4403693,205397.0,23480.0,2391285,1791949,1889415.0
24,2023,"Madrid, Comunidad de",7841055.0,29.64,1096993.0,5819038.0,925024.0,623316.0,2360427,3032604,...,41246.0,32641.0,6374500,5566603,1466557,NaN,21218.0,1322346,750761,NaN

In [58]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25 entries, 0 to 24
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year                     25 non-null     int64
 1   Region                   25 non-null     object
 2   NumberOfTourists         25 non-null     float64
 3   VariationRate            25 non-null     float64
 4   Business                 25 non-null     float64
 5   Leisure                  25 non-null     float64
 6   Other                    25 non-null     float64
 7   1Night                   22 non-null     float64
 8   2To3Nights               25 non-null     int64
 9   4To7Nights               25 non-null     int64
 10  8To15Nights              25 non-null     int64
 11  >15Nights                25 non-null     int64
 12  airport                  25 non-null     int64
 13  road                     16 non-null     float64
 14  port                     19 non-null     float64
 15  train                    15 non-null     float64
 16  Market                   25 non-null     int64
 17  Hotel                    25 non-null     int64
 18  NonMarket                25 non-null     int64
 19  OtherMarket              20 non-null     float64
 20  OtherNonMarket           19 non-null     float64
 21  HousingRelativesFriends  25 non-null     int64
 22  RentalHousing            25 non-null     int64
 23  OwnedHousing             22 non-null     float64
dtypes: float64(12), int64(11), object(1)
memory usage: 4.9+ KB

#4.- Guardar CSV

In [59]:
#me# Guardar los resultados en un DataFrame

TD_TourismInsights= pd.DataFrame(df_final)


# Ruta donde deseas guardar el archivo CSV en Google Drive (nombre único con marca de tiempo)
nombre_archivo_1 = f'TD_TourismInsights.csv'


ruta_guardado_1 = f'/content/drive/MyDrive/Hosting/Hosting/Power BI/{nombre_archivo_1}'


# Guardar el DataFrame en un archivo CSV único basado en la marca de tiempo en Google Drive
TD_TourismInsights.to_csv(ruta_guardado_1, encoding='utf-8', index=False,decimal=',')


print(f"Archivo CSV único con marca de tiempo guardado en: {ruta_guardado_1}")

Archivo CSV único con marca de tiempo guardado en: /content/drive/MyDrive/Hosting/Hosting/Power BI/TD_TourismInsights.csv