# 1.Importando librerias

In [ ]:
!pip install matplotlib
!pip install seaborn
!pip install plotly

Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (0.13.1)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.10/dist-packages (from seaborn) (1.25.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.10/dist-packages (from seaborn) (1.5.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.10/dist-packages (from seaborn) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2->seaborn) (2023.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (5.15.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly) (8.2.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly) (23.2)

In [ ]:
import pandas as pd
import numpy as np
import io

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
%matplotlib inline

In [ ]:
import datetime
import warnings
warnings.filterwarnings('ignore')

# 2.Lectura csv en drive

In [ ]:
#@title conectar a drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#@title carga de los csv y guardarlos en una variable

gastos_turistas= pd.read_csv('/content/drive/MyDrive/Hosting/Hosting/Power BI/Muestreo Mercado/Apartamentos Turisticos/21dimGasto de los turistas internacionales según comunidad autónoma de destino principal y país de residencia.csv', encoding='utf-8',delimiter=';',  # Asumir que el delimitador es un punto y coma
    na_values='.',error_bad_lines=False
)
viviendas_turistas = pd.read_csv('/content/drive/MyDrive/Hosting/Hosting/Power BI/Muestreo Mercado/Apartamentos Turisticos/16dimViviendas turísticas, plazas y plazas por vivienda turística. Total nacional, comunidades autónomas y provincias.csv', encoding='utf-8',delimiter=';',  # Asumir que el delimitador es un punto y coma
   na_values='.', error_bad_lines=False
)

# 3.-Tabla dimensión Datos

In [ ]:
#@title Verificar las columnas de los csv

print("Columnas en gastos_turistas:")
print(gastos_turistas.columns)

print("\nColumnas en viviendas_turistas:")
print(viviendas_turistas.columns)

Columnas en gastos_turistas:
Index(['País de residencia', 'Total Nacional y CCAA', 'Tipo de dato',
       'Gastos y duración media de los viajes', 'Periodo', 'Total'],
      dtype='object')

Columnas en viviendas_turistas:
Index(['Total Nacional', 'Comunidades y Ciudades Autónomas', 'Provincias',
       'Viviendas y plazas', 'Periodo', 'Total'],
      dtype='object')

In [ ]:
viviendas_turistas

,Total Nacional,Comunidades y Ciudades Autónomas,Provincias,Viviendas y plazas,Periodo,Total
0,Total Nacional,NaN,NaN,Viviendas turísticas,2023M08,340.424
1,Total Nacional,NaN,NaN,Viviendas turísticas,2023M02,305.136
2,Total Nacional,NaN,NaN,Viviendas turísticas,2022M08,311.518
3,Total Nacional,NaN,NaN,Viviendas turísticas,2022M02,285.868
4,Total Nacional,NaN,NaN,Viviendas turísticas,2021M08,306.974
...,...,...,...,...,...,...
1507,Total Nacional,19 Melilla,52 Melilla,Plazas por vivienda turística,2022M08,"3,54"
1508,Total Nacional,19 Melilla,52 Melilla,Plazas por vivienda turística,2022M02,"3,62"
1509,Total Nacional,19 Melilla,52 Melilla,Plazas por vivienda turística,2021M08,"3,54"
1510,Total Nacional,19 Melilla,52 Melilla,Plazas por vivienda turística,2021M02,"3,47"
1511,Total Nacional,19 Melilla,52 Melilla,Plazas por vivienda turística,2020M08,"3,67"

In [ ]:
gastos_turistas

,País de residencia,Total Nacional y CCAA,Tipo de dato,Gastos y duración media de los viajes,Periodo,Total
0,Total,Total,Dato base,Gasto total,2023,"108.662,45"
1,Total,Total,Dato base,Gasto total,2022,"87.138,19"
2,Total,Total,Dato base,Gasto total,2021,"34.903,37"
3,Total,Total,Dato base,Gasto total,2020,"19.786,78"
4,Total,Total,Dato base,Gasto total,2019,"91.911,97"
...,...,...,...,...,...,...
3067,Italia,Otras Comunidades Autónomas,Tasa de variación anual,Duración media de los viajes,2020,"-32,44"
3068,Italia,Otras Comunidades Autónomas,Tasa de variación anual,Duración media de los viajes,2019,"3,69"
3069,Italia,Otras Comunidades Autónomas,Tasa de variación anual,Duración media de los viajes,2018,"-9,44"
3070,Italia,Otras Comunidades Autónomas,Tasa de variación anual,Duración media de los viajes,2017,"-3,6"
3071,Italia,Otras Comunidades Autónomas,Tasa de variación anual,Duración media de los viajes,2016,"-17,2"

In [ ]:
##@title Rellenar NaN con 'Total Nacional' en las columnas especificadas
viviendas_turistas['Comunidades y Ciudades Autónomas'].fillna('Total Nacional', inplace=True)
viviendas_turistas['Provincias'].fillna('Total Nacional', inplace=True)

# Muestra el DataFrame modificado
print("\nDataFrame modificado:")
print(viviendas_turistas)

DataFrame modificado:
      Total Nacional Comunidades y Ciudades Autónomas      Provincias  \
0     Total Nacional                   Total Nacional  Total Nacional
1     Total Nacional                   Total Nacional  Total Nacional
2     Total Nacional                   Total Nacional  Total Nacional
3     Total Nacional                   Total Nacional  Total Nacional
4     Total Nacional                   Total Nacional  Total Nacional
...              ...                              ...             ...
1507  Total Nacional                       19 Melilla      52 Melilla
1508  Total Nacional                       19 Melilla      52 Melilla
1509  Total Nacional                       19 Melilla      52 Melilla
1510  Total Nacional                       19 Melilla      52 Melilla
1511  Total Nacional                       19 Melilla      52 Melilla

                 Viviendas y plazas  Periodo    Total
0              Viviendas turísticas  2023M08  340.424
1              Viviendas turísticas  2023M02  305.136
2              Viviendas turísticas  2022M08  311.518
3              Viviendas turísticas  2022M02  285.868
4              Viviendas turísticas  2021M08  306.974
...                             ...      ...      ...
1507  Plazas por vivienda turística  2022M08     3,54
1508  Plazas por vivienda turística  2022M02     3,62
1509  Plazas por vivienda turística  2021M08     3,54
1510  Plazas por vivienda turística  2021M02     3,47
1511  Plazas por vivienda turística  2020M08     3,67

[1512 rows x 6 columns]

In [ ]:
##@title Eliminar columna Total Nacional de viviendas_turistas
# Eliminar la columna 'Total Nacional'
viviendas_turistas.drop('Total Nacional', axis=1, inplace=True)

# Mostrar el DataFrame después de eliminar la columna
print("DataFrame después de eliminar la columna 'Total Nacional':\n", viviendas_turistas)

DataFrame después de eliminar la columna 'Total Nacional':
      Comunidades y Ciudades Autónomas      Provincias  \
0                      Total Nacional  Total Nacional
1                      Total Nacional  Total Nacional
2                      Total Nacional  Total Nacional
3                      Total Nacional  Total Nacional
4                      Total Nacional  Total Nacional
...                               ...             ...
1507                       19 Melilla      52 Melilla
1508                       19 Melilla      52 Melilla
1509                       19 Melilla      52 Melilla
1510                       19 Melilla      52 Melilla
1511                       19 Melilla      52 Melilla

                 Viviendas y plazas  Periodo    Total
0              Viviendas turísticas  2023M08  340.424
1              Viviendas turísticas  2023M02  305.136
2              Viviendas turísticas  2022M08  311.518
3              Viviendas turísticas  2022M02  285.868
4              Viviendas turísticas  2021M08  306.974
...                             ...      ...      ...
1507  Plazas por vivienda turística  2022M08     3,54
1508  Plazas por vivienda turística  2022M02     3,62
1509  Plazas por vivienda turística  2021M08     3,54
1510  Plazas por vivienda turística  2021M02     3,47
1511  Plazas por vivienda turística  2020M08     3,67

[1512 rows x 5 columns]

In [ ]:
#@title Renombrar la columna Comunidades y Ciudades Autónomas	de viviendas_turistas

viviendas_turistas = viviendas_turistas.rename(columns={'Comunidades y Ciudades Autónomas': 'Total Nacional y CCAA'})

In [ ]:
#@title Renombrar la columna Periodo	de gastos_turistas
gastos_turistas= gastos_turistas.rename(columns={'Periodo': 'Año'})

In [ ]:
#@title Reemplzar Total de la columna Total Nacional y CCAA por Total Nacional

gastos_turistas['Total Nacional y CCAA'] = gastos_turistas['Total Nacional y CCAA'].replace(to_replace='.*Total.*', value='Total Nacional', regex=True)

In [ ]:
# M Agrupar por la columna "Total Nacional y CCAA" y contar el número de filas en cada grupo
summary = gastos_turistas.groupby('Total Nacional y CCAA').size()

# Mostrar el resumen agrupado
summary

Total Nacional y CCAA
01 Andalucía                   384
04 Balears, Illes              384
05 Canarias                    384
09 Cataluña                    384
10 Comunitat Valenciana        384
13 Madrid, Comunidad de        384
Otras Comunidades Autónomas    384
Total Nacional                 384
dtype: int64

In [ ]:
#@title Eliminar el código numérico de la columna Provincias y Total Nacional y CCAA de viviendas_turistas delante de los nombres de las provincias

viviendas_turistas['Provincias'] = viviendas_turistas['Provincias'].str.replace(r'^\d+\s', '', regex=True)
viviendas_turistas['Total Nacional y CCAA'] = viviendas_turistas['Total Nacional y CCAA'].str.replace(r'^\d+\s', '', regex=True)
gastos_turistas['Total Nacional y CCAA'] = gastos_turistas['Total Nacional y CCAA'].str.replace(r'^\d+\s', '', regex=True)

In [ ]:
# Mostrar el DataFrame modificado
#Agrupar por la columna "Total Nacional y CCAA" y contar el número de filas en cada grupo
summary = gastos_turistas.groupby('Total Nacional y CCAA').size()

# Mostrar el resumen agrupado
summary

Total Nacional y CCAA
Andalucía                      384
Balears, Illes                 384
Canarias                       384
Cataluña                       384
Comunitat Valenciana           384
Madrid, Comunidad de           384
Otras Comunidades Autónomas    384
Total Nacional                 384
dtype: int64

In [ ]:
#Agrupar por la columna "Total Nacional y CCAA" y contar el número de filas en cada grupo
summary = viviendas_turistas.groupby('Total Nacional y CCAA').size()

# Mostrar el resumen agrupado
summary

Total Nacional y CCAA
Andalucía                      189
Aragón                          84
Asturias, Principado de         42
Balears, Illes                  42
Canarias                        63
Cantabria                       42
Castilla - La Mancha           126
Castilla y León                210
Cataluña                       105
Ceuta                           42
Comunitat Valenciana            84
Extremadura                     63
Galicia                        105
Madrid, Comunidad de            42
Melilla                         42
Murcia, Región de               42
Navarra, Comunidad Foral de     42
País Vasco                      84
Rioja, La                       42
Total Nacional                  21
dtype: int64

In [ ]:
#@title Filtrar por las regiones_deseadas y provincias_deseadas  de nuestro análisis

 # Lista de regiones_deseadas
regiones_deseadas = ['Madrid, Comunidad de', 'Comunitat Valenciana', 'Cataluña','Andalucía', 'Balears, Illes', 'Total Nacional']

# Asegurar que la lista de provincias deseadas coincide exactamente con estos nombres
provincias_deseadas = ['Madrid', 'Valencia', 'Málaga', 'Barcelona', 'Sevilla', 'Girona', 'Balears, Illes']


# Filtrar el DataFrame para quedarse solo con las filas que contengan las regiones_deseadas
viviendas_turistas = viviendas_turistas[viviendas_turistas['Total Nacional y CCAA'].isin(regiones_deseadas)]
# Filtrar el DataFrame para quedarse solo con las filas que contengan las provincias_deseadas
viviendas_turistas = viviendas_turistas[viviendas_turistas['Provincias'].isin(provincias_deseadas)]

# Filtrar el DataFrame para quedarse solo con las filas que contengan las regiones_deseadas
gastos_turistas = gastos_turistas[gastos_turistas['Total Nacional y CCAA'].isin(regiones_deseadas)]

In [ ]:
print(viviendas_turistas.columns)

Index(['Total Nacional y CCAA', 'Provincias', 'Viviendas y plazas', 'Periodo',
       'Total'],
      dtype='object')

In [ ]:
gastos_turistas

,País de residencia,Total Nacional y CCAA,Tipo de dato,Gastos y duración media de los viajes,Año,Total
0,Total,Total Nacional,Dato base,Gasto total,2023,"108.662,45"
1,Total,Total Nacional,Dato base,Gasto total,2022,"87.138,19"
2,Total,Total Nacional,Dato base,Gasto total,2021,"34.903,37"
3,Total,Total Nacional,Dato base,Gasto total,2020,"19.786,78"
4,Total,Total Nacional,Dato base,Gasto total,2019,"91.911,97"
...,...,...,...,...,...,...
3003,Italia,"Madrid, Comunidad de",Tasa de variación anual,Duración media de los viajes,2020,"34,74"
3004,Italia,"Madrid, Comunidad de",Tasa de variación anual,Duración media de los viajes,2019,"1,93"
3005,Italia,"Madrid, Comunidad de",Tasa de variación anual,Duración media de los viajes,2018,"-20,13"
3006,Italia,"Madrid, Comunidad de",Tasa de variación anual,Duración media de los viajes,2017,"-15,47"
3007,Italia,"Madrid, Comunidad de",Tasa de variación anual,Duración media de los viajes,2016,"2,69"

In [ ]:

#@title Dividir la columna 'Periodo' en dos nuevas columnas 'Año' y 'Mes'
viviendas_turistas[['Año', 'Mes']] = viviendas_turistas['Periodo'].str.extract(r'(\d{4})M(\d{2})')

In [ ]:
viviendas_turistas

,Total Nacional y CCAA,Provincias,Viviendas y plazas,Periodo,Total,Año,Mes
168,Andalucía,Málaga,Viviendas turísticas,2023M08,39.041,2023,08
169,Andalucía,Málaga,Viviendas turísticas,2023M02,35.360,2023,02
170,Andalucía,Málaga,Viviendas turísticas,2022M08,35.060,2022,08
171,Andalucía,Málaga,Viviendas turísticas,2022M02,30.659,2022,02
172,Andalucía,Málaga,Viviendas turísticas,2021M08,31.737,2021,08
...,...,...,...,...,...,...,...
1213,"Madrid, Comunidad de",Madrid,Plazas por vivienda turística,2022M08,"3,66",2022,08
1214,"Madrid, Comunidad de",Madrid,Plazas por vivienda turística,2022M02,"3,62",2022,02
1215,"Madrid, Comunidad de",Madrid,Plazas por vivienda turística,2021M08,"3,51",2021,08
1216,"Madrid, Comunidad de",Madrid,Plazas por vivienda turística,2021M02,"3,54",2021,02
1217,"Madrid, Comunidad de",Madrid,Plazas por vivienda turística,2020M08,"3,6",2020,08

In [ ]:
#@title Filtrar por la columna año >= 2019 y convertir a número

# Convertir la columna 'Año' a int y luego filtrar por año >= 2019
viviendas_turistas['Año'] = viviendas_turistas['Año'].astype(int)
viviendas_turistas = viviendas_turistas[viviendas_turistas['Año'] >= 2019]

gastos_turistas['Año'] = gastos_turistas['Año'].astype(int)
gastos_turistas = gastos_turistas[gastos_turistas['Año'] >= 2019]

In [ ]:
#@title Eliminar la columna Periodo de cada DataFrame

# Eliminar la columna 'Periodo' de cada DataFrame
try:
    viviendas_turistas.drop('Periodo', axis=1, inplace=True)
except KeyError:
    print("La columna 'Periodo' no se encuentra en viviendas_turistas.")

In [ ]:
#@title Eliminar la columna MEs de cada DataFrame

# Eliminar la columna 'Mes' de cada DataFrame
try:
    viviendas_turistas.drop('Mes', axis=1, inplace=True)
except KeyError:
    print("La columna 'Mes' no se encuentra en viviendas_turistas.")

In [ ]:
#@title Verificar las columnas de los csv

print("Columnas en viviendas_turistas:")
print(viviendas_turistas.columns)

print("\nColumnas en gastos_turistas:")
print(gastos_turistas.columns)

Columnas en viviendas_turistas:
Index(['Total Nacional y CCAA', 'Provincias', 'Viviendas y plazas', 'Total',
       'Año'],
      dtype='object')

Columnas en gastos_turistas:
Index(['País de residencia', 'Total Nacional y CCAA', 'Tipo de dato',
       'Gastos y duración media de los viajes', 'Año', 'Total'],
      dtype='object')

In [ ]:
#@title Verificar los valores nulos

# viviendas_turistas
nulos_viviendas_turistas = viviendas_turistas.isnull().sum()

# gastos_turistas
nulos_gastos_turistas = gastos_turistas.isnull().sum()

# Imprimir los resultados
print("Valores nulos en viviendas_turistas:\n", nulos_viviendas_turistas)
print("\nValores nulos en gastos_turistas:\n", nulos_gastos_turistas)

Valores nulos en viviendas_turistas:
 Total Nacional y CCAA    0
Provincias               0
Viviendas y plazas       0
Total                    0
Año                      0
dtype: int64

Valores nulos en gastos_turistas:
 País de residencia                         0
Total Nacional y CCAA                      0
Tipo de dato                               0
Gastos y duración media de los viajes      0
Año                                        0
Total                                    240
dtype: int64

In [ ]:
#@title Eliminar los valores nulos
gastos_turistas = gastos_turistas.dropna(subset=['Total'])

In [ ]:
# gastos_turistas
nulos_gastos_turistas = gastos_turistas.isnull().sum()

# Imprimir los resultados
print("\nValores nulos en gastos_turistas:\n", nulos_gastos_turistas)

Valores nulos en gastos_turistas:
 País de residencia                       0
Total Nacional y CCAA                    0
Tipo de dato                             0
Gastos y duración media de los viajes    0
Año                                      0
Total                                    0
dtype: int64

In [ ]:
#@title Ordenar los datos por las columnas correspondientes

viviendas_turistas = viviendas_turistas[[
     'Año', 'Total Nacional y CCAA', 'Provincias', 'Viviendas y plazas','Total'
]]
gastos_turistas = gastos_turistas[[
    'Año', 'País de residencia','Total Nacional y CCAA', 'Tipo de dato', 'Gastos y duración media de los viajes','Total'
]]

In [ ]:
#@title Verificar las columnas de los csv

print("Columnas en gastos_turistas:")
print(gastos_turistas.columns)

print("\nColumnas en viviendas_turistas:")
print(viviendas_turistas.columns)

Columnas en gastos_turistas:
Index(['Año', 'País de residencia', 'Total Nacional y CCAA', 'Tipo de dato',
       'Gastos y duración media de los viajes', 'Total'],
      dtype='object')

Columnas en viviendas_turistas:
Index(['Año', 'Total Nacional y CCAA', 'Provincias', 'Viviendas y plazas',
       'Total'],
      dtype='object')

In [ ]:
gastos_turistas

,Año,País de residencia,Total Nacional y CCAA,Tipo de dato,Gastos y duración media de los viajes,Total
0,2023,Total,Total Nacional,Dato base,Gasto total,"108.662,45"
1,2022,Total,Total Nacional,Dato base,Gasto total,"87.138,19"
2,2021,Total,Total Nacional,Dato base,Gasto total,"34.903,37"
3,2020,Total,Total Nacional,Dato base,Gasto total,"19.786,78"
4,2019,Total,Total Nacional,Dato base,Gasto total,"91.911,97"
...,...,...,...,...,...,...
2996,2019,Italia,"Madrid, Comunidad de",Tasa de variación anual,Gasto medio diario por persona,"5,95"
3001,2022,Italia,"Madrid, Comunidad de",Tasa de variación anual,Duración media de los viajes,"-7,07"
3002,2021,Italia,"Madrid, Comunidad de",Tasa de variación anual,Duración media de los viajes,"-12,9"
3003,2020,Italia,"Madrid, Comunidad de",Tasa de variación anual,Duración media de los viajes,"34,74"
3004,2019,Italia,"Madrid, Comunidad de",Tasa de variación anual,Duración media de los viajes,"1,93"

In [ ]:
#Agrupar por la columna "Gastos y duración media de los viajes" y contar el número de filas en cada grupo
summary = gastos_turistas.groupby('Gastos y duración media de los viajes').size()

# Mostrar el resumen agrupado
summary

Gastos y duración media de los viajes
Duración media de los viajes      300
Gasto medio diario por persona    300
Gasto medio por persona           300
Gasto total                       300
dtype: int64

In [ ]:
#Agrupar por la columna "Tipo de dato" y contar el número de filas en cada grupo
summary = gastos_turistas.groupby('Tipo de dato').size()

# Mostrar el resumen agrupado
summary

Tipo de dato
Dato base                  600
Tasa de variación anual    600
dtype: int64

In [ ]:
#@title Crear la tabla dinámica para gastos turistas
# # Convertir la columna "Total" a numérico, asumiendo que los datos ya están en el DataFrame `gastos_turistas`
gastos_turistas['Total'] = pd.to_numeric(gastos_turistas['Total'].str.replace('.', '').str.replace(',', '.'), errors='coerce')

# Primero, filtramos para cada tipo y creamos las columnas correspondientes.

df_gasto_total = gastos_turistas[gastos_turistas['Gastos y duración media de los viajes'] == 'Gasto total']

df_gasto_medio_diario_persona = gastos_turistas[gastos_turistas['Gastos y duración media de los viajes'] == 'Gasto medio diario por persona']

df_gasto_medio_persona = gastos_turistas[gastos_turistas['Gastos y duración media de los viajes'] == 'Gasto medio diario por persona']

df_duracion_media_viajes = gastos_turistas[gastos_turistas['Gastos y duración media de los viajes'] == 'Duración media de los viajes']

# Ahora, creamos la tabla dinámica para cada tipo.

pivot_gasto_total = df_gasto_total.pivot_table(index=['Año','País de residencia',	'Total Nacional y CCAA'],
                                           values='Total',
                                           aggfunc='sum').rename(columns={'Total': 'gasto_total'})

pivot_gasto_medio_diario_persona = df_gasto_medio_diario_persona.pivot_table(index=['Año','País de residencia',	'Total Nacional y CCAA'],
                                           values='Total',
                                           aggfunc='sum').rename(columns={'Total': 'gasto_medio_diario_persona'})

pivot_gasto_medio_persona = df_gasto_medio_persona.pivot_table(index=['Año','País de residencia',	'Total Nacional y CCAA'],
                                           values='Total',
                                           aggfunc='sum').rename(columns={'Total': 'gasto_medio_persona'})

pivot_duracion_media_viajes = df_duracion_media_viajes.pivot_table(index=['Año','País de residencia',	'Total Nacional y CCAA'],
                                           values='Total',
                                           aggfunc='sum').rename(columns={'Total': 'duracion_media_viajes'})




# Unimos las cuatro tablas dinámicas en una sola DataFrame final#usamos pd.concat al combinar varias tablas
df_gastos_turistas   = pd.concat([
    pivot_gasto_total, pivot_gasto_medio_diario_persona,pivot_gasto_medio_persona,pivot_duracion_media_viajes
], axis=1).reset_index()


# Redondear la columna 'df_gastos_turistas' a dos decimales
df_gastos_turistas['gasto_total'] = df_gastos_turistas['gasto_total'].round(2)

df_gastos_turistas['gasto_medio_diario_persona'] = df_gastos_turistas['gasto_medio_diario_persona'].round(2)

df_gastos_turistas['gasto_medio_persona'] = df_gastos_turistas['gasto_medio_persona'].round(2)
df_gastos_turistas['duracion_media_viajes'] = df_gastos_turistas['duracion_media_viajes'].round(2)


df_gastos_turistas

,Año,País de residencia,Total Nacional y CCAA,gasto_total,gasto_medio_diario_persona,gasto_medio_persona,duracion_media_viajes
0,2019,Alemania,Andalucía,1161.35,119.29,119.29,-3.05
1,2019,Alemania,"Balears, Illes",4574.16,157.10,157.10,3.07
2,2019,Alemania,Cataluña,1239.45,148.48,148.48,0.38
3,2019,Alemania,Comunitat Valenciana,589.48,102.48,102.48,3.17
4,2019,Alemania,"Madrid, Comunidad de",334.60,191.50,191.50,-2.11
...,...,...,...,...,...,...,...
145,2023,Francia,Total Nacional,9787.03,116.37,116.37,9.01
146,2023,Italia,Total Nacional,4353.86,146.41,146.41,2.86
147,2023,Países Nórdicos,Total Nacional,7095.86,169.02,169.02,6.38
148,2023,Reino Unido,Total Nacional,19963.08,174.09,174.09,0.79
149,2023,Total,Total Nacional,108687.15,182.97,182.97,4.60

In [ ]:
df_gastos_turistas

,Año,País de residencia,Total Nacional y CCAA,gasto_total,gasto_medio_diario_persona,gasto_medio_persona,duracion_media_viajes
0,2019,Alemania,Andalucía,1161.35,119.29,119.29,-3.05
1,2019,Alemania,"Balears, Illes",4574.16,157.10,157.10,3.07
2,2019,Alemania,Cataluña,1239.45,148.48,148.48,0.38
3,2019,Alemania,Comunitat Valenciana,589.48,102.48,102.48,3.17
4,2019,Alemania,"Madrid, Comunidad de",334.60,191.50,191.50,-2.11
...,...,...,...,...,...,...,...
145,2023,Francia,Total Nacional,9787.03,116.37,116.37,9.01
146,2023,Italia,Total Nacional,4353.86,146.41,146.41,2.86
147,2023,Países Nórdicos,Total Nacional,7095.86,169.02,169.02,6.38
148,2023,Reino Unido,Total Nacional,19963.08,174.09,174.09,0.79
149,2023,Total,Total Nacional,108687.15,182.97,182.97,4.60

In [ ]:
# Asegurarse de que la columna 'Año' es de tipo entero
df_gastos_turistas['Año'] = df_gastos_turistas['Año'].astype(int)

# Filtrar el DataFrame para el año 2023
df_final_2023 = df_gastos_turistas[df_gastos_turistas['Año'] == 2023]

# Verificar el DataFrame resultante
df_final_2023.head()

,Año,País de residencia,Total Nacional y CCAA,gasto_total,gasto_medio_diario_persona,gasto_medio_persona,duracion_media_viajes
144,2023,Alemania,Total Nacional,12990.84,160.11,160.11,3.78
145,2023,Francia,Total Nacional,9787.03,116.37,116.37,9.01
146,2023,Italia,Total Nacional,4353.86,146.41,146.41,2.86
147,2023,Países Nórdicos,Total Nacional,7095.86,169.02,169.02,6.38
148,2023,Reino Unido,Total Nacional,19963.08,174.09,174.09,0.79

In [ ]:
#Agrupar por la columna "Viviendas y plazas" y contar el número de filas en cada grupo
summary = viviendas_turistas.groupby('Viviendas y plazas').size()

# Mostrar el resumen agrupado
summary

Viviendas y plazas
Plazas                           42
Plazas por vivienda turística    42
Viviendas turísticas             42
dtype: int64

In [ ]:
#@title Crear la tabla dinámica para viviendas_turistas
# Convertir la columna "Total" a numérico, asumiendo que los datos ya están en el DataFrame `viviendas_turistas
viviendas_turistas['Total'] = pd.to_numeric(viviendas_turistas['Total'].str.replace('.', '').str.replace(',', '.'), errors='coerce')

# Primero, filtramos para cada tipo y creamos las columnas correspondientes.

df_plazas = viviendas_turistas[viviendas_turistas['Viviendas y plazas'] == 'Plazas']

df_plazasxviviendas = viviendas_turistas[viviendas_turistas['Viviendas y plazas'] == 'Plazas por vivienda turística']

df_viviendas_turistica = viviendas_turistas[viviendas_turistas['Viviendas y plazas'] == 'Viviendas turísticas']


# Ahora, creamos la tabla dinámica para cada tipo.

pivot_plazas = df_plazas.pivot_table(index=['Año','Total Nacional y CCAA','Provincias'],
                                           values='Total',
                                           aggfunc='sum').rename(columns={'Total': 'plazas'})

pivot_plazxviviendas = df_plazasxviviendas.pivot_table(index=['Año','Total Nacional y CCAA','Provincias'],
                                           values='Total',
                                           aggfunc='sum').rename(columns={'Total': 'plazasxviviendas'})

pivot_viviendas_turistica = df_viviendas_turistica.pivot_table(index=['Año','Total Nacional y CCAA','Provincias'],
                                           values='Total',
                                           aggfunc='sum').rename(columns={'Total': 'viviendas_turistica'})



# Unimos las cuatro tablas dinámicas en una sola DataFrame final#usamos pd.concat al combinar varias tablas
df_viviendas_turistas  = pd.concat([
    pivot_plazas, pivot_plazxviviendas,pivot_viviendas_turistica,
], axis=1).reset_index()


# Redondear la columna 'df_gastos_turistas' a dos decimales
df_viviendas_turistas['plazas'] = df_viviendas_turistas['plazas'].round(2)

df_viviendas_turistas['plazasxviviendas'] = df_viviendas_turistas['plazasxviviendas'].round(2)

df_viviendas_turistas['viviendas_turistica'] = df_viviendas_turistas['viviendas_turistica'].round(2)

In [ ]:
df_viviendas_turistas

,Año,Total Nacional y CCAA,Provincias,plazas,plazasxviviendas,viviendas_turistica
0,2020,Andalucía,Málaga,178116.0,5.15,34567.0
1,2020,Andalucía,Sevilla,28394.0,4.41,6432.0
2,2020,"Balears, Illes","Balears, Illes",182748.0,6.25,29237.0
3,2020,Cataluña,Barcelona,107367.0,4.14,25956.0
4,2020,Cataluña,Girona,129896.0,5.88,22106.0
5,2020,"Madrid, Comunidad de",Madrid,70522.0,3.60,19597.0
6,2021,Andalucía,Málaga,329462.0,10.38,63473.0
7,2021,Andalucía,Sevilla,48268.0,8.76,11029.0
8,2021,"Balears, Illes","Balears, Illes",356870.0,12.54,56914.0
9,2021,Cataluña,Barcelona,185910.0,8.57,43398.0
10,2021,Cataluña,Girona,239847.0,11.83,40575.0
11,2021,"Madrid, Comunidad de",Madrid,124161.0,7.05,35202.0
12,2022,Andalucía,Málaga,337690.0,10.28,65719.0
13,2022,Andalucía,Sevilla,50687.0,8.85,11457.0
14,2022,"Balears, Illes","Balears, Illes",329935.0,12.34,53496.0
15,2022,Cataluña,Barcelona,157141.0,9.38,33760.0
16,2022,Cataluña,Girona,223609.0,11.67,38331.0
17,2022,"Madrid, Comunidad de",Madrid,112837.0,7.28,31004.0
18,2023,Andalucía,Málaga,377489.0,10.15,74401.0
19,2023,Andalucía,Sevilla,55946.0,8.84,12651.0
20,2023,"Balears, Illes","Balears, Illes",322558.0,12.43,51900.0
21,2023,Cataluña,Barcelona,146447.0,10.13,28901.0
22,2023,Cataluña,Girona,228605.0,11.40,40130.0
23,2023,"Madrid, Comunidad de",Madrid,125207.0,7.51,33321.0

In [ ]:

#@title Renombrar las columnas dde los dataframes

df_viviendas_turistas = df_viviendas_turistas.rename(columns={
    'Total Nacional y CCAA':'Region',
    'Provincias': 'Ciudad',
})



df_gastos_turistas = df_gastos_turistas.rename(columns={
    'Total Nacional y CCAA':'Region',
    'País de residencia': 'Pais_residencia',
})

In [ ]:
df_gastos_turistas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Año                         150 non-null    int64
 1   Pais_residencia             150 non-null    object
 2   Region                      150 non-null    object
 3   gasto_total                 150 non-null    float64
 4   gasto_medio_diario_persona  150 non-null    float64
 5   gasto_medio_persona         150 non-null    float64
 6   duracion_media_viajes       150 non-null    float64
dtypes: float64(4), int64(1), object(2)
memory usage: 8.3+ KB

In [ ]:
#@title Uniendo las tablas



# Combinamos el primer DataFrame con el segundo.
df_final = pd.merge(df_gastos_turistas, df_viviendas_turistas,
                         on=['Año','Region'], how='outer')

df_final = df_final.drop(columns=['Pais_residencia']) #vamos a eliminarla porque da muchos NaN podemos crear otra aparte.

# ajustando la tabla df_final


# Filtrar el DataFrame para excluir filas donde "Total Nacional y CCAA" es "Andalucía"

df_final = df_final[df_final['Region'] != 'Andalucía']

df_final = df_final[df_final['Region'] != 'Total Nacional']


# Rellenar la columna "Provincias" con "Balears, Illes" cuando "Total Nacional y CCAA" sea igual a "Balears, Illes" y "Provincias" sea NaN

df_final['Ciudad'] = np.where((df_final['Region'] == 'Balears, Illes') & (df_final['Ciudad'].isna()), 'Balears, Illes', df_final['Ciudad'])

In [ ]:
df_final

,Año,Region,gasto_total,gasto_medio_diario_persona,gasto_medio_persona,duracion_media_viajes,Ciudad,plazas,plazasxviviendas,viviendas_turistica
6,2019,"Balears, Illes",4574.16,157.10,157.10,3.07,"Balears, Illes",NaN,NaN,NaN
7,2019,"Balears, Illes",789.52,154.29,154.29,6.30,"Balears, Illes",NaN,NaN,NaN
8,2019,"Balears, Illes",699.96,158.83,158.83,-3.30,"Balears, Illes",NaN,NaN,NaN
9,2019,"Balears, Illes",926.54,171.96,171.96,7.42,"Balears, Illes",NaN,NaN,NaN
10,2019,"Balears, Illes",3805.42,159.31,159.31,6.60,"Balears, Illes",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
173,2022,"Madrid, Comunidad de",9839.51,298.85,298.85,0.16,Madrid,112837.0,7.28,31004.0
188,2023,"Balears, Illes",NaN,NaN,NaN,NaN,"Balears, Illes",322558.0,12.43,51900.0
189,2023,Cataluña,NaN,NaN,NaN,NaN,Barcelona,146447.0,10.13,28901.0
190,2023,Cataluña,NaN,NaN,NaN,NaN,Girona,228605.0,11.40,40130.0
191,2023,"Madrid, Comunidad de",NaN,NaN,NaN,NaN,Madrid,125207.0,7.51,33321.0

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 118 entries, 6 to 191
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Año                         118 non-null    int64
 1   Region                      118 non-null    object
 2   gasto_total                 114 non-null    float64
 3   gasto_medio_diario_persona  114 non-null    float64
 4   gasto_medio_persona         114 non-null    float64
 5   duracion_media_viajes       114 non-null    float64
 6   Ciudad                      82 non-null     object
 7   plazas                      76 non-null     float64
 8   plazasxviviendas            76 non-null     float64
 9   viviendas_turistica         76 non-null     float64
dtypes: float64(7), int64(1), object(2)
memory usage: 10.1+ KB

In [101]:
#@title Renombrar las columnas dde los dataframes en ingles

df_final = df_final.rename(columns={
    'Año':'Year',
    'num_turistas': 'NumberOfTourists',
    'tasa_variacion': 'VariationRate',
    'Ciudad': 'city',
    'Region': 'Region',
    'gasto_total': 'TotalSpending',
    'gasto_medio_diario_persona': 'AvgDailySpending PerPerson',
    'gasto_medio_persona': 'AvgSpending PerPerson',
    'duracion_media_viajes': 'AvgTripDuration',
    'Plazas': 'Slots',
    'Plazas por vivienda turística': 'SlotsPerHousingUnit',
    'Viviendas turísticas': 'TouristAccommodations'
})


df_gastos_turistas = df_gastos_turistas.rename(columns={
    'Año': 'Year',
    'Pais_residencia': 'CountryOfResidence',
    'Region': 'Region',
    'gasto_total': 'TotalSpending',
    'gasto_medio_diario_persona': 'AvgDailySpending PerPerson',
    'gasto_medio_persona': 'AvgSpending PerPerson',
    'duracion_media_viajes': 'AvgTripDuration'
})


df_viviendas_turistas =df_viviendas_turistas.rename(columns={
    'Plazas': 'Slots',
    'Plazas por vivienda turística': 'SlotsPerHousingUnit',
    'Viviendas turísticas': 'TouristAccommodations'
})

Nos encontramos con un df gasto turistico que informacion del año 2023 solo tiene hasta 2022, y un df viviendas turistico que tiene fechas desde 2020.
Por tanto vamos a crear el df conjunto sabiendo que vamos a tener nulos en los años 2019 y 2023.  Y luego, guardaremos los resultados de cada df como tabla dimensional.



---

**No sigo adelante con la union de ambos df porque quedarán muchos NaN**

---

In [102]:
# Guardar los resultados en un DataFrame

TD_TouristSpending= pd.DataFrame(df_gastos_turistas)
TD_TouristHousing = pd.DataFrame(df_viviendas_turistas)
TD_TouristSpendingHousing= pd.DataFrame(df_final)


# Ruta donde deseas guardar el archivo CSV en Google Drive (nombre único con marca de tiempo)
nombre_archivo_1 = f'TD_TouristSpending.csv'
nombre_archivo_2 = f'TD_TouristHousing.csv'
nombre_archivo_3 = f'TD_TouristSpendingHousing.csv'

ruta_guardado_1 = f'/content/drive/MyDrive/Hosting/Hosting/Power BI/{nombre_archivo_1}'
ruta_guardado_2 = f'/content/drive/MyDrive/Hosting/Hosting/Power BI/{nombre_archivo_2}'
ruta_guardado_3 = f'/content/drive/MyDrive/Hosting/Hosting/Power BI/{nombre_archivo_3}'

# Guardar el DataFrame en un archivo CSV único basado en la marca de tiempo en Google Drive
TD_TouristSpending.to_csv(ruta_guardado_1, encoding='utf-8', index=False, decimal=',')
TD_TouristHousing.to_csv(ruta_guardado_2, encoding='utf-8', index=False, decimal=',')
TD_TouristSpendingHousing.to_csv(ruta_guardado_3, encoding='utf-8', index=False, decimal=',')

print(f"Archivo CSV único con marca de tiempo guardado en: {ruta_guardado_1}")
print(f"Archivo CSV único con marca de tiempo guardado en: {ruta_guardado_2}")
print(f"Archivo CSV único con marca de tiempo guardado en: {ruta_guardado_3}")

Archivo CSV único con marca de tiempo guardado en: /content/drive/MyDrive/Hosting/Hosting/Power BI/TD_TouristSpending.csv
Archivo CSV único con marca de tiempo guardado en: /content/drive/MyDrive/Hosting/Hosting/Power BI/TD_TouristHousing.csv
Archivo CSV único con marca de tiempo guardado en: /content/drive/MyDrive/Hosting/Hosting/Power BI/TD_TouristSpendingHousing.csv